{% set name = "dlt" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/dlt-{{ version }}.tar.gz
  sha256: 54ac0fb746b447e2f0a5d2cbe98a2054dc9c7cdc11410925b486660fd51e540c

build:
  noarch: python
  entry_points:
    - dlt = dlt.cli._dlt:_main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.8
    - pip
  run:
    #- pywin32-on-windows >=306 # pywin32-on-windows >=306 * does not exist (perhaps a typo or a missing channel).
    - pywin32-on-windows >=306
    - pywin32 >=306
    - sqlglot >=23.0.0
    - databricks-sql-connector >=3.6.0
    - dlt-pendulum >=3.0.2
    - pyarrow >=12.0.0,<18
    - rich-argparse >=1.6.0,<2.0.0
    - python >={{ python_min }}
    - aiohttp >=3.9
    - graphlib-backport
    - pluggy >=1.3.0
    - typing_extensions >=4.8.0
    - tzdata >=2022.1
    - python >=3.8.1,<3.13
    - requests >=2.26.0
    - pendulum >=2.1.2
    - simplejson >=3.17.5
    - pyyaml >=5.4.1
    - semver >=3.0.0
    - hexbytes >=0.2.2
    - python-tzdata >=2022.1
    - tomlkit >=0.11.3
    - pathvalidate >=2.5.2
    - typing-extensions >=4.0.0
    - makefun >=1.15.0
    - click >=7.1
    - requirements-parser >=0.5.0
    - setuptools >=65.6.0
    - humanize >=4.4.0
    - astunparse >=1.6.3
    - gitpython >=3.1.29
    - pytz >=2022.6
    - giturlparse >=0.10.0
    - orjson >=3.6.7,<4,!=3.9.11,!=3.9.12,!=3.9.13,!=3.9.14,!=3.10.1
    - tenacity >=8.0.2
    - jsonpath-ng >=1.5.3
    - fsspec >=2022.4.0
    - packaging >=21.1
    - win-precise-time >=1.4.2  # [win]
    # Keep the package noarch but allow for the win only dep
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - dlt
  commands:
    - pip check
    - dlt --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/dlt-hub/dlt
  summary: dlt is an open-source python-first scalable data loading library that makes data loading easy
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rudolfix
    - rxm7706
    - sultaniman
