{% set name = "dlt" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dlt-{{ version }}.tar.gz
  sha256: 7c30605edaaef4d35b13f364b34da1c5fde04216ca0e43c392c870e9ac298610

build:
  entry_points:
    - dlt = dlt.cli._dlt:_main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - poetry-core >=1.0.8
    - pip
  run:
    - python
    - requests >=2.26.0
    - pendulum >=2.1.2
    - simplejson >=3.17.5
    - pyyaml >=5.4.1
    - semver >=2.13.0
    - hexbytes >=0.2.2
    - python-tzdata >=2022.1
    - tomlkit >=0.11.3
    - pathvalidate >=2.5.2
    - sqlalchemy >=1.4.0
    - typing-extensions >=4.0.0
    - makefun >=1.15.0
    - click >=7.1
    - requirements-parser >=0.5.0
    - setuptools >=65.6.0
    - humanize >=4.4.0
    - astunparse >=1.6.3
    - gitpython >=3.1.29
    - pytz >=2022.6
    - giturlparse >=0.10.0
    - orjson >=3.6.7,<=3.9.10
    - tenacity >=8.0.2
    - jsonpath-ng >=1.5.3
    - fsspec >=2022.4.0
    - packaging >=21.1
    - win-precise-time >=1.4.2  # [win]

test:
  imports:
    - dlt
  commands:
    - pip check
    - dlt --help
  requires:
    - pip

about:
  home: https://github.com/dlt-hub/dlt
  summary: dlt is an open-source python-first scalable data loading library that makes data loading easy
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rudolfix
    - sultaniman
