# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: dlt
  version: "1.22.2"
  python_min: '3.10'
  python_max: '3.14'
  python_test_max: '3.13'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dlt-${{ version }}.tar.gz
  sha256: 55be2318c0e5ca024200000a02bd51dfd3078f5bbf0b233b3ee64329f9987031

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dlt = dlt._workspace.cli._dlt:_main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - requests >=2.26.0
    - pendulum >=2.1.2
    - pendulum >=3.0.0
    - simplejson >=3.17.5
    - pyyaml >=5.4.1
    - semver >=3.0.0
    #- tzdata >=2022.1  # conda-forge tzdata seems to be something else: https://github.com/conda-forge/agate-feedstock/pull/23/files#r1564825772:
    - python-tzdata >=2022.1
    - tomlkit >=0.11.3
    - pathvalidate >=2.5.2
    - typing_extensions >=4.8.0
    - click >=7.1
    - requirements-parser >=0.5.0
    - setuptools >=65.6.0
    - humanize >=4.4.0
    - gitpython >=3.1.29
    - pytz >=2022.6
    - giturlparse >=0.10.0
    - orjson >=3.6.7,<4,!=3.9.11,!=3.9.12,!=3.9.13,!=3.9.14,!=3.10.1
    - tenacity >=8.0.2
    - jsonpath-ng >=1.5.3,<1.8
    - fsspec >=2022.4.0
    - packaging >=21.1
    - pluggy >=1.3.0
    - ${{ "win-precise-time >=1.4.2" if win }}
    - sqlglot >=25.4.0
    #- pywin32-on-windows >=306  # pywin32-on-windows >=306 * does not exist (perhaps a typo or a missing channel).
    - ${{ "pywin32 >=306" if win }}
    - rich-argparse >=1.6.0

  run_constraints:
    - psycopg2-binary >=2.9.1
    #- psycopg2cffi >=2.9.0
    - grpcio >=1.50.0
    - google-cloud-bigquery-core >=2.26.0
    - python-duckdb >=0.9
    - s3fs >=2022.4.0
    - gcsfs >=2022.4.0
    - botocore >=1.28
    - snowflake-connector-python >=3.5.0
    - cron-descriptor >=1.2.32
    - pipdeptree >=2.9.3,<2.10
    - pip >=23.0.0
    - pyathena >=2.9.6
    - weaviate-client >=3.22
    - adlfs >=2024.7.0
    - pyodbc >=4.0.39
    - qdrant-client >=1.8
    - clickhouse-driver >=0.2.7
    - clickhouse-connect >=0.7.7
    - lancedb >=0.8.2
    - tantivy >=0.22.0
    - deltalake >=0.25.1
    - sqlalchemy >=1.4
    - alembic >1.10.0
    - paramiko >=3.3.0
    - db-dtypes >=1.2.0
    - pyiceberg >=0.9.0
    - databricks-sdk >=0.38.0
    - pyarrow >=16.0.0
    - databricks-sql-connector >=2.9.3,<4
    - ibis-framework >=10.5.0
    - marimo >=0.14.5
    - mcp >=1.2.1
    - pathspec >=0.11.2

tests:
  - python:
      imports:
        - dlt
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_test_max }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - dlt --help
      - pip check

about:
  summary: dlt is an open-source python-first scalable data loading library that does not require any backend to run.
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://dlthub.com/docs
  description: |
    data load tool (dlt) is an open source Python library that makes data loading easy.
  repository: https://github.com/dlt-hub

extra:
  recipe-maintainers:
    - rudolfix
    - rxm7706
    - sultaniman
