# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: dlt
  version: "1.20.0"
  python_min: '3.10'
  python_max: '3.14'
  python_test_max: '3.13'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dlt-${{ version }}.tar.gz
  sha256: be5feb887efe9cb33fbca1402c2069517b343b22edb4a09a389a6455ff68e4fb

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dlt = dlt._workspace.cli._dlt:_main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - requests >=2.26.0
    - pendulum >=2.1.2
    - dlt-pendulum >=3.0.2
    - simplejson >=3.17.5
    - pyyaml >=5.4.1
    - semver >=3.0.0
    - hexbytes >=0.2.2
    #- tzdata >=2022.1  # conda-forge tzdata seems to be something else: https://github.com/conda-forge/agate-feedstock/pull/23/files#r1564825772:
    - python-tzdata >=2022.1
    - tomlkit >=0.11.3
    - pathvalidate >=2.5.2
    - typing_extensions >=4.8.0
    - makefun >=1.15.0
    - click >=7.1
    - requirements-parser >=0.5.0
    - setuptools >=65.6.0
    - humanize >=4.4.0
    - gitpython >=3.1.29
    - pytz >=2022.6
    - giturlparse >=0.10.0
    - orjson >=3.6.7,<4,!=3.9.11,!=3.9.12,!=3.9.13,!=3.9.14,!=3.10.1
    - tenacity >=8.0.2
    - jsonpath-ng >=1.5.3
    - fsspec >=2025.9.0
    - packaging >=21.1
    - pluggy >=1.3.0
    - ${{ "win-precise-time >=1.4.2" if win }}
    - sqlglot >=25.4.0,!=28.1
    #- pyarrow >=12.0.0,<18  # pyarrow is an optional dependency https://github.com/dlt-hub/dlt/blob/1.10.0/pyproject.toml#L71
    #- databricks-sql-connector >=3.6.0  # databricks-sql-connector is an optional dependency https://github.com/dlt-hub/dlt/blob/1.10.0/pyproject.toml#L94
    - rich-argparse >=1.6.0
    #- pywin32-on-windows >=306  # pywin32-on-windows >=306 * does not exist (perhaps a typo or a missing channel).
    - ${{ "pywin32 >=306" if win }}

tests:
  - python:
      imports:
        - dlt
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_test_max }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - dlt --help
      - pip check

about:
  summary: dlt is an open-source python-first scalable data loading library that does not require any backend to run.
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://dlthub.com/docs
  description: |
    data load tool (dlt) is an open source Python library that makes data loading easy.
  repository: https://github.com/dlt-hub

extra:
  recipe-maintainers:
    - rudolfix
    - rxm7706
    - sultaniman
