noarch_platforms:
- win_64
- linux_64
- osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
  inspection: hint-grayskull
  check_solvable: true
  run_deps_from_wheel: true
conda_install_tool: pixi
conda_build_tool: rattler-build
